//
//  EventNames.swift
//  Flow
//
//  Created by Kevin Chan on 09/12/2017.
//  Copyright © 2017 MusicG. All rights reserved.
//

struct EventNames {
    static let VIEW_FINISH_LOADING = "VIEW_FINISH_LOADING"
    static let MEASURE_UPDATE = "MEASURE_UPDATE"
    static let ADD_NEW_NOTE = "ADD_NEW_NOTE"
    static let MEASURE_SWITCHED = "MEASURE_SWITCHED"
    static let STAFF_SWITCHED = "STAFF_SWITCHED"

    static let NOTATION_KEY_PRESSED = "NOTATION_KEY_PRESSED"
    static let ARROW_KEY_PRESSED = "ARROW_KEY_PRESSED"
    static let DELETE_KEY_PRESSED = "DELETE_KEY_PRESSED"
    
    static let UPDATE_INVALID_NOTES = "UPDATE_INVALID_NOTES"

    static let COPY_KEY_PRESSED = "COPY_KEY_PRESSED"
    static let CUT_KEY_PRESSED = "CUT_KEY_PRESSED"
    static let PASTE_KEY_PRESSED = "PASTE_KEY_PRESSED"
    
    static let PLAY_KEY_PRESSED = "PLAY_KEY_PRESSED"
    static let STOP_PLAYBACK = "STOP_PLAYBACK"

    static let EDIT_TIME_SIG = "EDIT_TIME_SIG"
    static let EDIT_KEY_SIG = "EDIT_KEY_SIG"
    static let EDIT_SIGNATURE = "EDIT_SIGNATURE"

    static let TITLE_CHANGED = "TITLE_CHANGED"

    static let NATURALIZE_KEY_PRESSED = "NATURALIZE_KEY_PRESSED"
    static let FLAT_KEY_PRESSED = "FLAT_KEY_PRESSED"
    static let SHARP_KEY_PRESSED = "SHARP_KEY_PRESSED"
    static let DSHARP_KEY_PRESSED = "DSHARP_KEY_PRESSED"

    static let ADD_GRAND_STAFF = "ADD_GRAND_STAFF"

    static let DISABLE_ACCIDENTALS = "DISABLE_ACCIDENTALS"
    static let ENABLE_ACCIDENTALS = "ENABLE_ACCIDENTALS"
    
    static let CHANGES_MADE = "CHANGES_MADE"

    static let HIGHLIGHT_MEASURE = "HIGHLIGHT_MEASURE"
    static let HIDE_TEMPO_MENU = "HIDE_TEMPO_MENU"
    
    static let SELECT_KEY_SIGNATURE = "SELECT_KEY_SIGNATURE"
}
